name: nappybrain
favicon: null
layout_spectrum: 1
typography_spectrum: 0.20059
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#b79464'
    - '#393836'
    - '#d1bea2'
    - '#0b0b0b'
    - '#4b6ca8'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.9974907736759633
purpose: []
