name: nappybrain
favicon: null
layout_spectrum: 0.6590553331188858
typography_spectrum: 0.6094153032172471
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#FF6700'
    - '#EBEBEB'
    - '#C0C0C0'
    - '#3A6EA5'
    - '#004E98'
  brandStrength: 0.7627888470888138
  lightness: 0.21484374185092747
  saturation: 0.5675556897185743
  rhythmicContrast: 0.9974907736759633
purpose: []
